[profile.default]
evm_version = "cancun"
ffi = true
fs_permissions = [{access = "read-write", path = ".forge-snapshots/"}]
libs = ["lib"]
out = "out"
solc_version = "0.8.30"
src = "src"
via_ir = false

[fuzz]
runs = 256

[invariant]
runs = 256
depth = 50
fail_on_revert = false

[profile.lint]
exclude_lints = ["screaming-snake-case-immutable", "screaming-snake-case-const"]

[profile.coverage]
include = ["src/**/*.sol"]
exclude = ["lib/**", "test/**", "script/**"]
report = "lcov"
